name: shread
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - gdal
  - requests
  - configparser
  - geojson
  - pandas
  - geopandas
  - fiona
  - lxml
  - rasterstats
  - rasterio
  - jupyter
  - tzlocal
  - netcdf4
  - xarray
  - rioxarray
  - pygrib
  - joblib